In [6]:
import pandas as pd
import numpy as np
import re
import pickle
import time, os

pd.set_option('display.max_rows', 308)

In [7]:
#compile pdfs into dataframe
columns = ['Circuit', 'Tiers', 'Start Date', 'Key Communities', 'End Date']
data = pd.DataFrame(columns = columns)

data = pd.concat([
    pd.read_csv("PSPS - 06.21.19.csv", names = columns),
    pd.read_csv("PSPS - 10.05.19.csv", names = columns),
    pd.read_csv("PSPS - 10.09.19.csv", names = columns),
    pd.read_csv("PSPS - 10.10.19.csv", names = columns),
    pd.read_csv("PSPS - 10.23.19.csv", names = columns),
    pd.read_csv("PSPS - 10.26.19.csv", names = columns),
    pd.read_csv("PSPS - 10.31.18.csv", names = columns),
    pd.read_csv("PSPS - 11.20.19.csv", names = columns)
], ignore_index = True, sort = False)

In [10]:
data.head()

,Circuit,Tiers,Start Date,Key Communities,End Date
0,BANGOR 1101,"TIER 2,\rTIER 3,\rPARTIALLY\rOUTSIDE\rHFTD",6/8/2019\r20:45,"BANGOR, BROWNS\rVALLEY,\rBROWNSVILLE,\rDOBBINS...",6/9/2019 12:35
1,BUTTE 1105*,"TIER 2,\rTIER 3,\rPARTIALLY\rOUTSIDE\rHFTD",6/8/2019\r20:55,CHICO,6/9/2019 13:57
2,CLARK ROAD\r1101,"TIER 2,\rPARTIALLY\rOUTSIDE\rHFTD",6/8/2019\r21:13,OROVILLE,6/9/2019 10:41
3,CLARK ROAD\r1102,"TIER 2,\rTIER 3,\rPARTIALLY\rOUTSIDE\rHFTD",6/8/2019\r21:13,"OROVILLE,\rPARADISE",6/9/2019 13:01
4,MONTICELLO\r1101,"TIER 2,\rZONE 1,\rPARTIALLY\rOUTSIDE\rHFTD",6/8/2019\r6:18,"LAKE BERRYESSA,\rNAPA, SUISUN CITY",6/8/2019 19:39

In [9]:
data.to_csv('data.csv')

## Data Cleaning

In [161]:
#drop columns
data = data.drop(columns = ['Circuit', 'Tiers'])

#limit key communities to one
data = data.applymap(lambda x: x.split('\r', 1)[0])
data = data.applymap(lambda x: x.split(',', 1)[0])
#data['Circuit'] = data['Circuit'].apply(lambda x: re.sub(r'[^a-zA-Z]', '', x))

#remove transmission line data
transmission_entries = data[data['Key Communities'] == 'Transmission Line'].index
data.drop(transmission_entries, inplace=True)

#remove rows with invalid dates
data['Start Date'] = data['Start Date'].replace(r'^([^0-9]*)$', np.nan, regex=True)
data = data.dropna()

#remove timestamps
data['Start Date'] = data['Start Date'].apply(lambda x: x.split(' ', 1)[0])
data['End Date'] = data['End Date'].apply(lambda x: x.split(' ', 1)[0])

#remove rows without full dates
data = data[data['Start Date'].str.contains('/')]

#format date column
data['Start Date'] = data['Start Date'].astype('datetime64')
data['End Date'] = data['End Date'].astype('datetime64') 

#proper capitalization on key communities
data['Key Communities'] = data['Key Communities'].apply(lambda x: x.title())

In [222]:
locations = pickle.load(open('locations','rb'))

In [162]:
data = data.merge(locations, on = 'Key Communities')

In [163]:
data['Shutoff']=True

columns = ['Key Communities', 'Start Date', 'Shutoff', 'Latitude', 'Longitude', 'End Date']
data = data[columns]

In [209]:
pickle.dump(data,open('data','wb'))

In [258]:
data = pickle.load(open('data','rb'))

## non-target data

In [130]:
comm_date_set = set()

def entered_data(row):
    index = row.name
    comm = row['Key Communities']
    date = row['Start Date']
    
    comm_date_set.add((comm, date))
    
data.apply(helper, axis = 1);

In [204]:
pairings = set()

for city in data['Key Communities'].unique():
    for days in pd.date_range(end = '2019-11-30', periods = 91):
        pairings.add((city, days))

pairings -= comm_date_set

In [215]:
power_on = []
for pair in pairings:
    power_ = {}
    power_['Key Communities'] = pair[0]
    power_['Start Date'] = pair[1]
    power_on.append(power_)
add_data = pd.DataFrame(power_on)
add_data['Shutoff'] = False

In [223]:
locations = pickle.load(open('locations','rb'))

In [230]:
add_data = add_data.merge(locations, on = 'Key Communities')

In [233]:
add_data['End Date'] = None

In [236]:
pickle.dump(add_data,open('add_data','wb'))

In [260]:
add_data = pickle.load(open('add_data','rb'))

In [262]:
total_data = pd.concat([data, add_data], ignore_index = True, sort = False)

## scrape weather data

In [197]:
from bs4 import BeautifulSoup
import requests
from fake_useragent import UserAgent
from IPython.core.display import display, HTML
import json

In [198]:
ua = UserAgent()
user_agent = {'User-agent': ua.random}
print(user_agent)

{'User-agent': 'Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.17 Safari/537.36'}

In [164]:
data['Start Date'].iloc[3].timestamp()

1569369600.0

In [102]:
weather_data = response.json()
page = response.text
soup = BeautifulSoup(page,"lxml")

In [115]:
weather_data['daily']['data'][0]

{'time': 1559890800,
 'summary': 'Clear throughout the day.',
 'icon': 'clear-day',
 'sunriseTime': 1559911200,
 'sunsetTime': 1559964720,
 'moonPhase': 0.17,
 'precipIntensity': 0.0002,
 'precipIntensityMax': 0.0017,
 'precipIntensityMaxTime': 1559962800,
 'precipProbability': 0.03,
 'precipType': 'rain',
 'temperatureHigh': 75.17,
 'temperatureHighTime': 1559956560,
 'temperatureLow': 58.36,
 'temperatureLowTime': 1559991000,
 'apparentTemperatureHigh': 74.67,
 'apparentTemperatureHighTime': 1559956560,
 'apparentTemperatureLow': 58.85,
 'apparentTemperatureLowTime': 1559991000,
 'dewPoint': 39.87,
 'humidity': 0.45,
 'pressure': 1014.9,
 'windSpeed': 5.53,
 'windGust': 22.28,
 'windGustTime': 1559952600,
 'windBearing': 299,
 'cloudCover': 0.07,
 'uvIndex': 8,
 'uvIndexTime': 1559937780,
 'visibility': 10,
 'ozone': 348,
 'temperatureMin': 51.74,
 'temperatureMinTime': 1559911860,
 'temperatureMax': 75.17,
 'temperatureMaxTime': 1559956560,
 'apparentTemperatureMin': 52.23,
 'apparentTemperatureMinTime': 1559911860,
 'apparentTemperatureMax': 74.67,
 'apparentTemperatureMaxTime': 1559956560}

In [117]:
high = weather_data['daily']['data'][0]['temperatureHigh']
low = weather_data['daily']['data'][0]['temperatureLow']
humidity = weather_data['daily']['data'][0]['humidity']
dewpoint = weather_data['daily']['data'][0]['dewPoint']
pressure = weather_data['daily']['data'][0]['pressure']
windspeed = weather_data['daily']['data'][0]['windSpeed']
windgust = weather_data['daily']['data'][0]['windGust']
cover = weather_data['daily']['data'][0]['cloudCover']
_ = [high, low, humidity, dewpoint, pressure, windspeed, windgust, cover]
_

[75.17, 58.36, 0.45, 39.87, 1014.9, 5.53, 22.28, 0.07]

In [288]:
total_data.head()

,Key Communities,Start Date,Shutoff,Latitude,Longitude,End Date
0,Bangor,2019-06-08,True,39.388612,-121.405314,2019-06-09 00:00:00
1,Bangor,2019-10-09,True,39.388612,-121.405314,2019-10-11 00:00:00
2,Bangor,2019-10-09,True,39.388612,-121.405314,2019-10-11 00:00:00
3,Bangor,2019-09-25,True,39.388612,-121.405314,2019-09-25 00:00:00
4,Bangor,2019-09-25,True,39.388612,-121.405314,2019-09-25 00:00:00

In [199]:
def weather(row):
    index = row.name
    
    darksky_key = 'a9d96eee310a6efe1876fff2ee93cec3'
    TIMESTAMP = str(row['Start Date'].timestamp()).split('.',1)[0]
    LAT = str(row['Latitude'])
    LONG = str(row['Longitude'])
    darksky_url = 'https://api.darksky.net/forecast/' + darksky_key + '/' + LAT + ',' + LONG + ',' + TIMESTAMP + '?exclude=currently,flags'
    
    response = requests.get(darksky_url, headers = user_agent)
    weather_data = response.json()

    total_data.loc[index, 'High'] = weather_data['daily']['data'][0]['temperatureHigh']
    total_data.loc[index, 'Low'] = weather_data['daily']['data'][0]['temperatureLow']
    total_data.loc[index, 'Humidity'] = weather_data['daily']['data'][0]['humidity']
    total_data.loc[index, 'Dewpoint'] = weather_data['daily']['data'][0]['dewPoint']
    total_data.loc[index, 'Pressure'] = weather_data['daily']['data'][0]['pressure']
    total_data.loc[index, 'Windspeed'] = weather_data['daily']['data'][0]['windSpeed']
    total_data.loc[index, 'Windgust'] = weather_data['daily']['data'][0]['windGust']
    total_data.loc[index, 'Cover'] = weather_data['daily']['data'][0]['cloudCover']

In [322]:
#total_data.apply(weather, axis = 1);

In [327]:
pickle.dump(total_data,open('total_data','wb'))

In [328]:
total_data = pickle.load(open('total_data','rb'))

In [326]:
total_data.nunique()

Key Communities     308
Start Date           92
Shutoff               2
Latitude            304
Longitude           304
End Date             21
High               5494
Low                4315
Humidity             98
Dewpoint           5537
Pressure            301
Windspeed          1357
Windgust           3028
Cover                98
dtype: int64

Key Communities            object
Start Date         datetime64[ns]
Shutoff                      bool
Latitude                  float64
Longitude                 float64
End Date                   object
High                      float64
Low                       float64
Humidity                  float64
Dewpoint                  float64
Pressure                  float64
Windspeed                 float64
Windgust                  float64
Cover                     float64
dtype: object

## FIX MY DATA

In [70]:
total_data = pickle.load(open('total_data','rb'))

In [71]:
total_data.columns

Index(['Key Communities', 'Start Date', 'Shutoff', 'Latitude', 'Longitude',
       'End Date', 'High', 'Low', 'Humidity', 'Dewpoint', 'Pressure',
       'Windspeed', 'Windgust', 'Cover'],
      dtype='object')

In [149]:
weather_by_day = total_data.loc[:, ['Key Communities', 'Start Date', 'High', 'Low', 'Humidity', 'Dewpoint', 'Pressure',
       'Windspeed', 'Windgust', 'Cover']].copy(deep=True)

target_df = total_data.loc[total_data['Shutoff']==True, ['Key Communities', 'Start Date', 'Shutoff', 'Latitude', 'Longitude',
       'End Date']].copy(deep=True)

other_data = total_data.loc[total_data['Shutoff']==False, ['Key Communities', 'Start Date', 'Shutoff', 'Latitude', 'Longitude',
       ]].copy(deep=True)

In [150]:
print([weather_by_day.shape, target_df.shape, other_data.shape])

[(28929, 10), (1461, 6), (27468, 5)]

### trial run

In [73]:
practice = target_df.iloc[0:5].copy(deep=True)

In [74]:
practice['Day'] = practice.apply(lambda row: pd.date_range(row['Start Date'], row['End Date']), axis=1)

In [79]:
practice = practice.explode('Day').reset_index() \
        .drop(columns=['index', 'Start Date'])

In [80]:
practice

,Key Communities,Shutoff,Latitude,Longitude,End Date,Day
0,Bangor,True,39.388612,-121.405314,2019-06-09 00:00:00,2019-06-08
1,Bangor,True,39.388612,-121.405314,2019-06-09 00:00:00,2019-06-09
2,Bangor,True,39.388612,-121.405314,2019-10-11 00:00:00,2019-10-09
3,Bangor,True,39.388612,-121.405314,2019-10-11 00:00:00,2019-10-10
4,Bangor,True,39.388612,-121.405314,2019-10-11 00:00:00,2019-10-11
5,Bangor,True,39.388612,-121.405314,2019-10-11 00:00:00,2019-10-09
6,Bangor,True,39.388612,-121.405314,2019-10-11 00:00:00,2019-10-10
7,Bangor,True,39.388612,-121.405314,2019-10-11 00:00:00,2019-10-11
8,Bangor,True,39.388612,-121.405314,2019-09-25 00:00:00,2019-09-25
9,Bangor,True,39.388612,-121.405314,2019-09-25 00:00:00,2019-09-25

In [81]:
practice2 = other_data[other_data['Key Communities'] == 'Bangor'].rename(columns={'Start Date': 'Day'})

In [82]:
practice2

      Key Communities        Day  Shutoff   Latitude   Longitude
16527          Bangor 2019-09-30    False  39.388612 -121.405314
16528          Bangor 2019-10-10    False  39.388612 -121.405314
16529          Bangor 2019-09-15    False  39.388612 -121.405314
16530          Bangor 2019-11-08    False  39.388612 -121.405314
16531          Bangor 2019-11-13    False  39.388612 -121.405314
16532          Bangor 2019-11-23    False  39.388612 -121.405314
16533          Bangor 2019-10-31    False  39.388612 -121.405314
16534          Bangor 2019-09-10    False  39.388612 -121.405314
16535          Bangor 2019-11-18    False  39.388612 -121.405314
16536          Bangor 2019-09-06    False  39.388612 -121.405314
16537          Bangor 2019-10-01    False  39.388612 -121.405314
16538          Bangor 2019-11-25    False  39.388612 -121.405314
16539          Bangor 2019-09-09    False  39.388612 -121.405314
16540          Bangor 2019-10-07    False  39.388612 -121.405314
16541          Bangor 2019-09-11    False  39.388612 -121.405314
16542          Bangor 2019-10-21    False  39.388612 -121.405314
16543          Bangor 2019-09-28    False  39.388612 -121.405314
16544          Bangor 2019-11-02    False  39.388612 -121.405314
16545          Bangor 2019-09-17    False  39.388612 -121.405314
16546          Bangor 2019-09-27    False  39.388612 -121.405314
16547          Bangor 2019-09-18    False  39.388612 -121.405314
16548          Bangor 2019-10-06    False  39.388612 -121.405314
16549          Bangor 2019-10-15    False  39.388612 -121.405314
16550          Bangor 2019-09-03    False  39.388612 -121.405314
16551          Bangor 2019-09-01    False  39.388612 -121.405314
16552          Bangor 2019-09-04    False  39.388612 -121.405314
16553          Bangor 2019-10-24    False  39.388612 -121.405314
16554          Bangor 2019-09-23    False  39.388612 -121.405314
16555          Bangor 2019-11-24    False  39.388612 -121.405314
16556          Bangor 2019-11-11    False  39.388612 -121.405314
16557          Bangor 2019-09-02    False  39.388612 -121.405314
16558          Bangor 2019-11-26    False  39.388612 -121.405314
16559          Bangor 2019-10-22    False  39.388612 -121.405314
16560          Bangor 2019-10-27    False  39.388612 -121.405314
16561          Bangor 2019-09-19    False  39.388612 -121.405314
16562          Bangor 2019-10-05    False  39.388612 -121.405314
16563          Bangor 2019-11-07    False  39.388612 -121.405314
16564          Bangor 2019-10-29    False  39.388612 -121.405314
16565          Bangor 2019-09-08    False  39.388612 -121.405314
16566          Bangor 2019-10-20    False  39.388612 -121.405314
16567          Bangor 2019-10-12    False  39.388612 -121.405314
16568          Bangor 2019-11-12    False  39.388612 -121.405314
16569          Bangor 2019-11-06    False  39.388612 -121.405314
16570          Bangor 2019-10-08    False  39.388612 -121.405314
16571          Bangor 2019-09-12    False  39.388612 -121.405314
16572          Bangor 2019-11-01    False  39.388612 -121.405314
16573          Bangor 2019-11-14    False  39.388612 -121.405314
16574          Bangor 2019-11-10    False  39.388612 -121.405314
16575          Bangor 2019-11-30    False  39.388612 -121.405314
16576          Bangor 2019-11-05    False  39.388612 -121.405314
16577          Bangor 2019-10-02    False  39.388612 -121.405314
16578          Bangor 2019-09-21    False  39.388612 -121.405314
16579          Bangor 2019-10-14    False  39.388612 -121.405314
16580          Bangor 2019-09-07    False  39.388612 -121.405314
16581          Bangor 2019-11-04    False  39.388612 -121.405314
16582          Bangor 2019-09-16    False  39.388612 -121.405314
16583          Bangor 2019-09-14    False  39.388612 -121.405314
16584          Bangor 2019-11-15    False  39.388612 -121.405314
16585          Bangor 2019-09-05    False  39.388612 -121.405314
16586          Bangor 2019-10-30    False  39.388612 -121.405314
16587          Bangor 2019-09-13    False  39.388612 -121.405314
16588          Bangor 2019-10-04    False  39.388612 -121.405314
16589          Bangor 2019-11-29    False  39.388612 -121.405314
16590          Bangor 2019-11-27    False  39.388612 -121.405314
16591          Bangor 2019-11-20    False  39.388612 -121.405314
16592          Bangor 2019-11-09    False  39.388612 -121.405314
16593          Bangor 2019-10-11    False  39.388612 -121.405314
16594          Bangor 2019-11-03    False  39.388612 -121.405314
16595          Bangor 2019-10-03    False  39.388612 -121.405314
16596          Bangor 2019-10-25    False  39.388612 -121.405314
16597          Bangor 2019-11-21    False  39.388612 -121.405314
16598          Bangor 2019-10-19    False  39.388612 -121.405314
16599          Bangor 2019-11-22    False  39.388612 -121.405314
16600          Bangor 2019-09-29    False  39.388612 -121.405314
16601          Bangor 2019-10-16    False  39.388612 -121.405314
16602          Bangor 2019-10-28    False  39.388612 -121.405314
16603          Bangor 2019-09-20    False  39.388612 -121.405314
16604          Bangor 2019-09-26    False  39.388612 -121.405314
16605          Bangor 2019-09-24    False  39.388612 -121.405314
16606          Bangor 2019-11-17    False  39.388612 -121.405314
16607          Bangor 2019-10-17    False  39.388612 -121.405314
16608          Bangor 2019-10-18    False  39.388612 -121.405314
16609          Bangor 2019-09-22    False  39.388612 -121.405314
16610          Bangor 2019-11-19    False  39.388612 -121.405314
16611          Bangor 2019-11-28    False  39.388612 -121.405314
16612          Bangor 2019-10-13    False  39.388612 -121.405314
16613          Bangor 2019-11-16    False  39.388612 -121.405314

In [87]:
stuff2drop = pd.merge(practice,practice2, on=['Key Communities', 'Day', 'Latitude', 'Longitude'], how='outer')

In [93]:
#loses rows because merge accounts for overlap in data where dates were originally marked false
#but are actually in date ranges of shutoffs
print([practice.shape, practice2.shape, stuff2drop.shape])

[(10, 6), (87, 5), (95, 7)]

In [94]:
stuff2drop

,Key Communities,Shutoff_x,Latitude,Longitude,End Date,Day,Shutoff_y
0,Bangor,True,39.388612,-121.405314,2019-06-09 00:00:00,2019-06-08,NaN
1,Bangor,True,39.388612,-121.405314,2019-06-09 00:00:00,2019-06-09,NaN
2,Bangor,True,39.388612,-121.405314,2019-10-11 00:00:00,2019-10-09,NaN
3,Bangor,True,39.388612,-121.405314,2019-10-11 00:00:00,2019-10-09,NaN
4,Bangor,True,39.388612,-121.405314,2019-10-11 00:00:00,2019-10-10,False
5,Bangor,True,39.388612,-121.405314,2019-10-11 00:00:00,2019-10-10,False
6,Bangor,True,39.388612,-121.405314,2019-10-11 00:00:00,2019-10-11,False
7,Bangor,True,39.388612,-121.405314,2019-10-11 00:00:00,2019-10-11,False
8,Bangor,True,39.388612,-121.405314,2019-09-25 00:00:00,2019-09-25,NaN
9,Bangor,True,39.388612,-121.405314,2019-09-25 00:00:00,2019-09-25,NaN
10,Bangor,NaN,39.388612,-121.405314,NaN,2019-09-30,False
11,Bangor,NaN,39.388612,-121.405314,NaN,2019-09-15,False
12,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-08,False
13,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-13,False
14,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-23,False
15,Bangor,NaN,39.388612,-121.405314,NaN,2019-10-31,False
16,Bangor,NaN,39.388612,-121.405314,NaN,2019-09-10,False
17,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-18,False
18,Bangor,NaN,39.388612,-121.405314,NaN,2019-09-06,False
19,Bangor,NaN,39.388612,-121.405314,NaN,2019-10-01,False
20,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-25,False
21,Bangor,NaN,39.388612,-121.405314,NaN,2019-09-09,False
22,Bangor,NaN,39.388612,-121.405314,NaN,2019-10-07,False
23,Bangor,NaN,39.388612,-121.405314,NaN,2019-09-11,False
24,Bangor,NaN,39.388612,-121.405314,NaN,2019-10-21,False
25,Bangor,NaN,39.388612,-121.405314,NaN,2019-09-28,False
26,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-02,False
27,Bangor,NaN,39.388612,-121.405314,NaN,2019-09-17,False
28,Bangor,NaN,39.388612,-121.405314,NaN,2019-09-27,False
29,Bangor,NaN,39.388612,-121.405314,NaN,2019-09-18,False
30,Bangor,NaN,39.388612,-121.405314,NaN,2019-10-06,False
31,Bangor,NaN,39.388612,-121.405314,NaN,2019-10-15,False
32,Bangor,NaN,39.388612,-121.405314,NaN,2019-09-03,False
33,Bangor,NaN,39.388612,-121.405314,NaN,2019-09-01,False
34,Bangor,NaN,39.388612,-121.405314,NaN,2019-09-04,False
35,Bangor,NaN,39.388612,-121.405314,NaN,2019-10-24,False
36,Bangor,NaN,39.388612,-121.405314,NaN,2019-09-23,False
37,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-24,False
38,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-11,False
39,Bangor,NaN,39.388612,-121.405314,NaN,2019-09-02,False
40,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-26,False
41,Bangor,NaN,39.388612,-121.405314,NaN,2019-10-22,False
42,Bangor,NaN,39.388612,-121.405314,NaN,2019-10-27,False
43,Bangor,NaN,39.388612,-121.405314,NaN,2019-09-19,False
44,Bangor,NaN,39.388612,-121.405314,NaN,2019-10-05,False
45,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-07,False
46,Bangor,NaN,39.388612,-121.405314,NaN,2019-10-29,False
47,Bangor,NaN,39.388612,-121.405314,NaN,2019-09-08,False
48,Bangor,NaN,39.388612,-121.405314,NaN,2019-10-20,False
49,Bangor,NaN,39.388612,-121.405314,NaN,2019-10-12,False
50,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-12,False
51,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-06,False
52,Bangor,NaN,39.388612,-121.405314,NaN,2019-10-08,False
53,Bangor,NaN,39.388612,-121.405314,NaN,2019-09-12,False
54,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-01,False
55,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-14,False
56,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-10,False
57,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-30,False
58,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-05,False
59,Bangor,NaN,39.388612,-121.405314,NaN,2019-10-02,False
60,Bangor,NaN,39.388612,-121.405314,NaN,2019-09-21,False
61,Bangor,NaN,39.388612,-121.405314,NaN,2019-10-14,False
62,Bangor,NaN,39.388612,-121.405314,NaN,2019-09-07,False
63,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-04,False
64,Bangor,NaN,39.388612,-121.405314,NaN,2019-09-16,False
65,Bangor,NaN,39.388612,-121.405314,NaN,2019-09-14,False
66,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-15,False
67,Bangor,NaN,39.388612,-121.405314,NaN,2019-09-05,False
68,Bangor,NaN,39.388612,-121.405314,NaN,2019-10-30,False
69,Bangor,NaN,39.388612,-121.405314,NaN,2019-09-13,False
70,Bangor,NaN,39.388612,-121.405314,NaN,2019-10-04,False
71,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-29,False
72,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-27,False
73,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-20,False
74,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-09,False
75,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-03,False
76,Bangor,NaN,39.388612,-121.405314,NaN,2019-10-03,False
77,Bangor,NaN,39.388612,-121.405314,NaN,2019-10-25,False
78,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-21,False
79,Bangor,NaN,39.388612,-121.405314,NaN,2019-10-19,False
80,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-22,False
81,Bangor,NaN,39.388612,-121.405314,NaN,2019-09-29,False
82,Bangor,NaN,39.388612,-121.405314,NaN,2019-10-16,False
83,Bangor,NaN,39.388612,-121.405314,NaN,2019-10-28,False
84,Bangor,NaN,39.388612,-121.405314,NaN,2019-09-20,False
85,Bangor,NaN,39.388612,-121.405314,NaN,2019-09-26,False
86,Bangor,NaN,39.388612,-121.405314,NaN,2019-09-24,False
87,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-17,False
88,Bangor,NaN,39.388612,-121.405314,NaN,2019-10-17,False
89,Bangor,NaN,39.388612,-121.405314,NaN,2019-10-18,False
90,Bangor,NaN,39.388612,-121.405314,NaN,2019-09-22,False
91,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-19,False
92,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-28,False
93,Bangor,NaN,39.388612,-121.405314,NaN,2019-10-13,False
94,Bangor,NaN,39.388612,-121.405314,NaN,2019-11-16,False

In [111]:
stuff2add = stuff2drop[stuff2drop['Shutoff_x'].isnull()]
stuff2add = stuff2add.drop(columns = ['Shutoff_x'])
stuff2add = stuff2add.rename(columns = {'Shutoff_y':'Shutoff'})

In [112]:
stuff2add

   Key Communities   Latitude   Longitude End Date        Day Shutoff
10          Bangor  39.388612 -121.405314      NaN 2019-09-30   False
11          Bangor  39.388612 -121.405314      NaN 2019-09-15   False
12          Bangor  39.388612 -121.405314      NaN 2019-11-08   False
13          Bangor  39.388612 -121.405314      NaN 2019-11-13   False
14          Bangor  39.388612 -121.405314      NaN 2019-11-23   False
15          Bangor  39.388612 -121.405314      NaN 2019-10-31   False
16          Bangor  39.388612 -121.405314      NaN 2019-09-10   False
17          Bangor  39.388612 -121.405314      NaN 2019-11-18   False
18          Bangor  39.388612 -121.405314      NaN 2019-09-06   False
19          Bangor  39.388612 -121.405314      NaN 2019-10-01   False
20          Bangor  39.388612 -121.405314      NaN 2019-11-25   False
21          Bangor  39.388612 -121.405314      NaN 2019-09-09   False
22          Bangor  39.388612 -121.405314      NaN 2019-10-07   False
23          Bangor  39.388612 -121.405314      NaN 2019-09-11   False
24          Bangor  39.388612 -121.405314      NaN 2019-10-21   False
25          Bangor  39.388612 -121.405314      NaN 2019-09-28   False
26          Bangor  39.388612 -121.405314      NaN 2019-11-02   False
27          Bangor  39.388612 -121.405314      NaN 2019-09-17   False
28          Bangor  39.388612 -121.405314      NaN 2019-09-27   False
29          Bangor  39.388612 -121.405314      NaN 2019-09-18   False
30          Bangor  39.388612 -121.405314      NaN 2019-10-06   False
31          Bangor  39.388612 -121.405314      NaN 2019-10-15   False
32          Bangor  39.388612 -121.405314      NaN 2019-09-03   False
33          Bangor  39.388612 -121.405314      NaN 2019-09-01   False
34          Bangor  39.388612 -121.405314      NaN 2019-09-04   False
35          Bangor  39.388612 -121.405314      NaN 2019-10-24   False
36          Bangor  39.388612 -121.405314      NaN 2019-09-23   False
37          Bangor  39.388612 -121.405314      NaN 2019-11-24   False
38          Bangor  39.388612 -121.405314      NaN 2019-11-11   False
39          Bangor  39.388612 -121.405314      NaN 2019-09-02   False
40          Bangor  39.388612 -121.405314      NaN 2019-11-26   False
41          Bangor  39.388612 -121.405314      NaN 2019-10-22   False
42          Bangor  39.388612 -121.405314      NaN 2019-10-27   False
43          Bangor  39.388612 -121.405314      NaN 2019-09-19   False
44          Bangor  39.388612 -121.405314      NaN 2019-10-05   False
45          Bangor  39.388612 -121.405314      NaN 2019-11-07   False
46          Bangor  39.388612 -121.405314      NaN 2019-10-29   False
47          Bangor  39.388612 -121.405314      NaN 2019-09-08   False
48          Bangor  39.388612 -121.405314      NaN 2019-10-20   False
49          Bangor  39.388612 -121.405314      NaN 2019-10-12   False
50          Bangor  39.388612 -121.405314      NaN 2019-11-12   False
51          Bangor  39.388612 -121.405314      NaN 2019-11-06   False
52          Bangor  39.388612 -121.405314      NaN 2019-10-08   False
53          Bangor  39.388612 -121.405314      NaN 2019-09-12   False
54          Bangor  39.388612 -121.405314      NaN 2019-11-01   False
55          Bangor  39.388612 -121.405314      NaN 2019-11-14   False
56          Bangor  39.388612 -121.405314      NaN 2019-11-10   False
57          Bangor  39.388612 -121.405314      NaN 2019-11-30   False
58          Bangor  39.388612 -121.405314      NaN 2019-11-05   False
59          Bangor  39.388612 -121.405314      NaN 2019-10-02   False
60          Bangor  39.388612 -121.405314      NaN 2019-09-21   False
61          Bangor  39.388612 -121.405314      NaN 2019-10-14   False
62          Bangor  39.388612 -121.405314      NaN 2019-09-07   False
63          Bangor  39.388612 -121.405314      NaN 2019-11-04   False
64          Bangor  39.388612 -121.405314      NaN 2019-09-16   False
65          Bangor  39.388612 -121.405314      NaN 2019-09-14   False
66          Bangor  39.388612 -121.405314      NaN 2019-11-15   False
67          Bangor  39.388612 -121.405314      NaN 2019-09-05   False
68          Bangor  39.388612 -121.405314      NaN 2019-10-30   False
69          Bangor  39.388612 -121.405314      NaN 2019-09-13   False
70          Bangor  39.388612 -121.405314      NaN 2019-10-04   False
71          Bangor  39.388612 -121.405314      NaN 2019-11-29   False
72          Bangor  39.388612 -121.405314      NaN 2019-11-27   False
73          Bangor  39.388612 -121.405314      NaN 2019-11-20   False
74          Bangor  39.388612 -121.405314      NaN 2019-11-09   False
75          Bangor  39.388612 -121.405314      NaN 2019-11-03   False
76          Bangor  39.388612 -121.405314      NaN 2019-10-03   False
77          Bangor  39.388612 -121.405314      NaN 2019-10-25   False
78          Bangor  39.388612 -121.405314      NaN 2019-11-21   False
79          Bangor  39.388612 -121.405314      NaN 2019-10-19   False
80          Bangor  39.388612 -121.405314      NaN 2019-11-22   False
81          Bangor  39.388612 -121.405314      NaN 2019-09-29   False
82          Bangor  39.388612 -121.405314      NaN 2019-10-16   False
83          Bangor  39.388612 -121.405314      NaN 2019-10-28   False
84          Bangor  39.388612 -121.405314      NaN 2019-09-20   False
85          Bangor  39.388612 -121.405314      NaN 2019-09-26   False
86          Bangor  39.388612 -121.405314      NaN 2019-09-24   False
87          Bangor  39.388612 -121.405314      NaN 2019-11-17   False
88          Bangor  39.388612 -121.405314      NaN 2019-10-17   False
89          Bangor  39.388612 -121.405314      NaN 2019-10-18   False
90          Bangor  39.388612 -121.405314      NaN 2019-09-22   False
91          Bangor  39.388612 -121.405314      NaN 2019-11-19   False
92          Bangor  39.388612 -121.405314      NaN 2019-11-28   False
93          Bangor  39.388612 -121.405314      NaN 2019-10-13   False
94          Bangor  39.388612 -121.405314      NaN 2019-11-16   False

In [113]:
stuff2add.columns

Index(['Key Communities', 'Latitude', 'Longitude', 'End Date', 'Day',
       'Shutoff'],
      dtype='object')

In [114]:
practice.columns

Index(['Key Communities', 'Shutoff', 'Latitude', 'Longitude', 'End Date',
       'Day'],
      dtype='object')

In [121]:
end_df = pd.concat([practice, stuff2add], sort=False).drop(columns=['End Date'])

In [123]:
end_df

   Key Communities Shutoff   Latitude   Longitude        Day
0           Bangor    True  39.388612 -121.405314 2019-06-08
1           Bangor    True  39.388612 -121.405314 2019-06-09
2           Bangor    True  39.388612 -121.405314 2019-10-09
3           Bangor    True  39.388612 -121.405314 2019-10-10
4           Bangor    True  39.388612 -121.405314 2019-10-11
5           Bangor    True  39.388612 -121.405314 2019-10-09
6           Bangor    True  39.388612 -121.405314 2019-10-10
7           Bangor    True  39.388612 -121.405314 2019-10-11
8           Bangor    True  39.388612 -121.405314 2019-09-25
9           Bangor    True  39.388612 -121.405314 2019-09-25
10          Bangor   False  39.388612 -121.405314 2019-09-30
11          Bangor   False  39.388612 -121.405314 2019-09-15
12          Bangor   False  39.388612 -121.405314 2019-11-08
13          Bangor   False  39.388612 -121.405314 2019-11-13
14          Bangor   False  39.388612 -121.405314 2019-11-23
15          Bangor   False  39.388612 -121.405314 2019-10-31
16          Bangor   False  39.388612 -121.405314 2019-09-10
17          Bangor   False  39.388612 -121.405314 2019-11-18
18          Bangor   False  39.388612 -121.405314 2019-09-06
19          Bangor   False  39.388612 -121.405314 2019-10-01
20          Bangor   False  39.388612 -121.405314 2019-11-25
21          Bangor   False  39.388612 -121.405314 2019-09-09
22          Bangor   False  39.388612 -121.405314 2019-10-07
23          Bangor   False  39.388612 -121.405314 2019-09-11
24          Bangor   False  39.388612 -121.405314 2019-10-21
25          Bangor   False  39.388612 -121.405314 2019-09-28
26          Bangor   False  39.388612 -121.405314 2019-11-02
27          Bangor   False  39.388612 -121.405314 2019-09-17
28          Bangor   False  39.388612 -121.405314 2019-09-27
29          Bangor   False  39.388612 -121.405314 2019-09-18
30          Bangor   False  39.388612 -121.405314 2019-10-06
31          Bangor   False  39.388612 -121.405314 2019-10-15
32          Bangor   False  39.388612 -121.405314 2019-09-03
33          Bangor   False  39.388612 -121.405314 2019-09-01
34          Bangor   False  39.388612 -121.405314 2019-09-04
35          Bangor   False  39.388612 -121.405314 2019-10-24
36          Bangor   False  39.388612 -121.405314 2019-09-23
37          Bangor   False  39.388612 -121.405314 2019-11-24
38          Bangor   False  39.388612 -121.405314 2019-11-11
39          Bangor   False  39.388612 -121.405314 2019-09-02
40          Bangor   False  39.388612 -121.405314 2019-11-26
41          Bangor   False  39.388612 -121.405314 2019-10-22
42          Bangor   False  39.388612 -121.405314 2019-10-27
43          Bangor   False  39.388612 -121.405314 2019-09-19
44          Bangor   False  39.388612 -121.405314 2019-10-05
45          Bangor   False  39.388612 -121.405314 2019-11-07
46          Bangor   False  39.388612 -121.405314 2019-10-29
47          Bangor   False  39.388612 -121.405314 2019-09-08
48          Bangor   False  39.388612 -121.405314 2019-10-20
49          Bangor   False  39.388612 -121.405314 2019-10-12
50          Bangor   False  39.388612 -121.405314 2019-11-12
51          Bangor   False  39.388612 -121.405314 2019-11-06
52          Bangor   False  39.388612 -121.405314 2019-10-08
53          Bangor   False  39.388612 -121.405314 2019-09-12
54          Bangor   False  39.388612 -121.405314 2019-11-01
55          Bangor   False  39.388612 -121.405314 2019-11-14
56          Bangor   False  39.388612 -121.405314 2019-11-10
57          Bangor   False  39.388612 -121.405314 2019-11-30
58          Bangor   False  39.388612 -121.405314 2019-11-05
59          Bangor   False  39.388612 -121.405314 2019-10-02
60          Bangor   False  39.388612 -121.405314 2019-09-21
61          Bangor   False  39.388612 -121.405314 2019-10-14
62          Bangor   False  39.388612 -121.405314 2019-09-07
63          Bangor   False  39.388612 -121.405314 2019-11-04
64          Bangor   False  39.388612 -121.405314 2019-09-16
65          Bangor   False  39.388612 -121.405314 2019-09-14
66          Bangor   False  39.388612 -121.405314 2019-11-15
67          Bangor   False  39.388612 -121.405314 2019-09-05
68          Bangor   False  39.388612 -121.405314 2019-10-30
69          Bangor   False  39.388612 -121.405314 2019-09-13
70          Bangor   False  39.388612 -121.405314 2019-10-04
71          Bangor   False  39.388612 -121.405314 2019-11-29
72          Bangor   False  39.388612 -121.405314 2019-11-27
73          Bangor   False  39.388612 -121.405314 2019-11-20
74          Bangor   False  39.388612 -121.405314 2019-11-09
75          Bangor   False  39.388612 -121.405314 2019-11-03
76          Bangor   False  39.388612 -121.405314 2019-10-03
77          Bangor   False  39.388612 -121.405314 2019-10-25
78          Bangor   False  39.388612 -121.405314 2019-11-21
79          Bangor   False  39.388612 -121.405314 2019-10-19
80          Bangor   False  39.388612 -121.405314 2019-11-22
81          Bangor   False  39.388612 -121.405314 2019-09-29
82          Bangor   False  39.388612 -121.405314 2019-10-16
83          Bangor   False  39.388612 -121.405314 2019-10-28
84          Bangor   False  39.388612 -121.405314 2019-09-20
85          Bangor   False  39.388612 -121.405314 2019-09-26
86          Bangor   False  39.388612 -121.405314 2019-09-24
87          Bangor   False  39.388612 -121.405314 2019-11-17
88          Bangor   False  39.388612 -121.405314 2019-10-17
89          Bangor   False  39.388612 -121.405314 2019-10-18
90          Bangor   False  39.388612 -121.405314 2019-09-22
91          Bangor   False  39.388612 -121.405314 2019-11-19
92          Bangor   False  39.388612 -121.405314 2019-11-28
93          Bangor   False  39.388612 -121.405314 2019-10-13
94          Bangor   False  39.388612 -121.405314 2019-11-16

### execute data clean

In [151]:
target_df.shape

(1461, 6)

In [152]:
target_df['Day'] = target_df.apply(lambda row: pd.date_range(row['Start Date'], row['End Date']), axis=1)

In [153]:
target_df = target_df.explode('Day').reset_index() \
        .drop(columns=['index', 'Start Date'])

In [154]:
other_data = other_data.rename(columns={'Start Date': 'Day'})

In [155]:
target_and_other = pd.merge(target_df,other_data, on=['Key Communities', 'Day', 'Latitude', 'Longitude'], how='outer')

In [156]:
#it worked!! removed false shutoff rows that overlapped with target data
print([target_df.shape, other_data.shape, target_and_other.shape])

[(4643, 6), (27468, 5), (30811, 7)]

In [157]:
add_to_target_df = target_and_other[target_and_other['Shutoff_x'].isnull()]
add_to_target_df = add_to_target_df.drop(columns = ['Shutoff_x']) \
                    .rename(columns = {'Shutoff_y':'Shutoff'})

In [264]:
df_final = pd.concat([target_df, add_to_target_df], sort=False).drop(columns=['End Date'])

In [173]:
weather_by_day = weather_by_day.rename(columns = {'Start Date':'Day'})

In [201]:
missing_weather = df_final[df_final['Day']=='2019-06-09T00:00:00.000000000'] \
                    .drop_duplicates() \
                    .drop(columns = 'Shutoff') \
                    .rename(columns = {'Day': 'Start Date'})

In [208]:
def weather2(row):
    index = row.name
    
    darksky_key = 'a9d96eee310a6efe1876fff2ee93cec3'
    TIMESTAMP = str(row['Start Date'].timestamp()).split('.',1)[0]
    LAT = str(row['Latitude'])
    LONG = str(row['Longitude'])
    darksky_url = 'https://api.darksky.net/forecast/' + darksky_key + '/' + LAT + ',' + LONG + ',' + TIMESTAMP + '?exclude=currently,flags'
    
    response = requests.get(darksky_url, headers = user_agent)
    weather_data = response.json()

    missing_weather.loc[index, 'High'] = weather_data['daily']['data'][0]['temperatureHigh']
    missing_weather.loc[index, 'Low'] = weather_data['daily']['data'][0]['temperatureLow']
    missing_weather.loc[index, 'Humidity'] = weather_data['daily']['data'][0]['humidity']
    missing_weather.loc[index, 'Dewpoint'] = weather_data['daily']['data'][0]['dewPoint']
    missing_weather.loc[index, 'Pressure'] = weather_data['daily']['data'][0]['pressure']
    missing_weather.loc[index, 'Windspeed'] = weather_data['daily']['data'][0]['windSpeed']
    missing_weather.loc[index, 'Windgust'] = weather_data['daily']['data'][0]['windGust']
    missing_weather.loc[index, 'Cover'] = weather_data['daily']['data'][0]['cloudCover']

In [211]:
#adds community+day combos to weather_data
missing_weather.apply(weather2, axis = 1);

In [212]:
missing_weather

,Key Communities,Latitude,Longitude,Start Date,High,Low,Humidity,Dewpoint,Pressure,Windspeed,Windgust,Cover
1,Bangor,39.388612,-121.405314,2019-06-09,82.79,66.98,0.23,32.03,1016.4,7.22,25.28,0.12
19,Chico,39.728494,-121.837478,2019-06-09,88.69,63.99,0.21,28.17,1017.6,9.15,19.56,0.11
76,Oroville,39.513775,-121.556359,2019-06-09,88.58,65.70,0.21,29.63,1016.8,9.08,19.93,0.11
201,Magalia,39.812106,-121.578306,2019-06-09,77.57,65.96,0.21,24.30,1018.0,8.76,29.20,0.12
228,Butte Meadows,40.081271,-121.551086,2019-06-09,69.68,52.96,0.27,20.13,1019.3,9.28,26.44,0.13
232,Paradise,39.759606,-121.621918,2019-06-09,83.09,68.19,0.20,25.49,1017.7,6.03,21.50,0.11
321,Berry Creek,39.645164,-121.403300,2019-06-09,78.33,62.85,0.24,26.72,1017.4,8.80,26.33,0.12

In [215]:
missing_weather = missing_weather.rename(columns = {'Start Date':'Day'}) \
                    .drop(columns = ['Latitude', 'Longitude'])
missing_weather

,Key Communities,Day,High,Low,Humidity,Dewpoint,Pressure,Windspeed,Windgust,Cover
1,Bangor,2019-06-09,82.79,66.98,0.23,32.03,1016.4,7.22,25.28,0.12
19,Chico,2019-06-09,88.69,63.99,0.21,28.17,1017.6,9.15,19.56,0.11
76,Oroville,2019-06-09,88.58,65.70,0.21,29.63,1016.8,9.08,19.93,0.11
201,Magalia,2019-06-09,77.57,65.96,0.21,24.30,1018.0,8.76,29.20,0.12
228,Butte Meadows,2019-06-09,69.68,52.96,0.27,20.13,1019.3,9.28,26.44,0.13
232,Paradise,2019-06-09,83.09,68.19,0.20,25.49,1017.7,6.03,21.50,0.11
321,Berry Creek,2019-06-09,78.33,62.85,0.24,26.72,1017.4,8.80,26.33,0.12

In [218]:
#weather_by_day.shape = (28929, 10)
weather_by_day = pd.concat([weather_by_day, missing_weather], sort=False)
#weather_by_day.shape = (28936, 10)

In [254]:
weather_by_day = weather_by_day.drop_duplicates()
weather_by_day.shape

(28214, 10)

In [332]:
weather_by_day = weather_by_day.drop_duplicates(['Key Communities','Day'],keep= 'last')
weather_by_day.shape

(28044, 10)

In [257]:
df_final.nunique()

Key Communities    308
Shutoff              2
Latitude           304
Longitude          304
Day                 93
dtype: int64

In [258]:
weather_by_day.nunique()

Key Communities     308
Day                  93
High               5494
Low                4315
Humidity             98
Dewpoint           5538
Pressure            301
Windspeed          1357
Windgust           3028
Cover                98
dtype: int64

In [259]:
df_final.Shutoff.value_counts()

False    26168
True      4643
Name: Shutoff, dtype: int64

In [260]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30811 entries, 0 to 30810
Data columns (total 5 columns):
Key Communities    30811 non-null object
Shutoff            30811 non-null object
Latitude           30811 non-null float64
Longitude          30811 non-null float64
Day                30811 non-null datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 1.4+ MB

In [338]:
model_data = pd.merge(df_final, weather_by_day, on = ['Key Communities', 'Day'])

In [342]:
model_data['Shutoff'] = model_data['Shutoff'].astype(bool)

In [343]:
pickle.dump(model_data,open('model_data','wb'))

In [2]:
model_data = pickle.load(open('model_data','rb'))

In [3]:
model_data.to_csv('model_data.csv')

In [4]:
model_data.head()

,Key Communities,Shutoff,Latitude,Longitude,Day,High,Low,Humidity,Dewpoint,Pressure,Windspeed,Windgust,Cover
0,Bangor,True,39.388612,-121.405314,2019-06-08,75.17,58.36,0.45,39.87,1014.9,5.53,22.28,0.07
1,Bangor,True,39.388612,-121.405314,2019-06-09,82.79,66.98,0.23,32.03,1016.4,7.22,25.28,0.12
2,Bangor,True,39.388612,-121.405314,2019-10-09,83.72,47.69,0.30,37.69,1010.9,3.46,9.85,0.22
3,Bangor,True,39.388612,-121.405314,2019-10-09,83.72,47.69,0.30,37.69,1010.9,3.46,9.85,0.22
4,Bangor,True,39.388612,-121.405314,2019-10-10,75.04,50.49,0.34,29.81,1012.0,5.84,22.82,0.00